library(shiny)
library(shinydashboard)
library(shinythemes)
library(shinyjs) 
library(readxl)
library(matrixcalc)
library(lattice)
library(ggplot2)
library(FrF2)
library(rsm)
library(openxlsx)
library(AlgDesign)
library(stringr)
library(mixexp)
options(warn = -1)
options(shiny.maxRequestSize = 30 * 1024 ^ 2)

