header<-dashboardHeader(title = "DoE",
                        tags$li(actionLink("openModal", label = "", 
                                           icon = icon("address-card")),
                                class = "dropdown")
                        )

sidebar<- dashboardSidebar(
    sidebarMenu(
                menuItem(text = "Variabili indipendenti",icon = shiny::icon("codepen"),
                         menuSubItem(text = "Fattoriale completo",tabName = "fatt_compl"),
                         menuSubItem(text = "Frazionario",tabName = "frazion"),
                         menuSubItem(text = "Plackett-Burman",tabName = "pb"),
                         menuSubItem(text = "CCD",tabName = "ccd"),
                         menuSubItem(text = "D-ottimale",tabName = "d_opt"),
                         menuSubItem(text = "Piano personalizzato",tabName = "pp")),
                menuItem(text = "Miscele",icon = shiny::icon("fill-drip"),
                         menuSubItem(text = "Simplex Design",tabName = "m_simplex"),
                         menuSubItem(text = "D-ottimale Design",tabName = "m_d_opt")),
                menuItem(text = "File",icon = icon("briefcase", lib = "font-awesome"),
                    actionButton("quit", "Quit",onclick = "setTimeout(function(){window.close();},200);",
                                      style='padding:4px; font-size:80%'))
                        ))

body<-dashboardBody(
  tabItems(
    tabItem(tabName = "fatt_compl",
        fluidPage(titlePanel(uiOutput("fatt_compl_titolo")),
                  tabsetPanel(type = "tabs",
                              tabPanel("Disegno",
                                       column(12,
                                              br()),
                                       column(4,
                                              numericInput("fatt_compl_k",label="n° fattori",width = "25%",value = 2,min = 1),
                                              h4('Disegno'),
                                              tableOutput("fatt_compl_dis"),
                                              downloadButton("fatt_compl_download")),
                                       column(8,
                                              plotOutput('fatt_compl_figura_dis')),
                                       column(12,
                                              hr(),
                                              h4('Modello'),
                                              textOutput("fatt_compl_modello")),
                                         column(12,
                                              hr(),
                                              h4('Matrice di dispersione'),
                                              div(style = 'overflow-x: scroll;',tableOutput("fatt_compl_matrdisp"))
                                              ),
                                       column(12,br(),
                                              h3('Grafico Leverage')),
                                       column(3,
                                              uiOutput('fatt_compl_selvar')),
                                       column(6,
                                              uiOutput('fatt_compl_fixvar')),
                                       column(12),
                                       column(6,
                                             plotOutput('fatt_compl_livellolev', width = "100%", height = "500px")
                                              ),
                                       column(6,
                                              plotOutput('fatt_compl_suplev', width = "100%", height = "500px")),
                                       column(6),
                                       column(3,
                                              br(),
                                              div(style='font-size: 80%; width: 90%;',
                                                  uiOutput('fatt_compl_lv_z'))),
                                       column(3,
                                              br(),
                                              div(style='font-size: 80%; width: 90%;',
                                                  uiOutput('fatt_compl_lv_x')))
                                       ),

                              tabPanel("Modello",
                                       column(4,
                                              br(),
                                              uiOutput('fatt_compl_risptext'),
                                              textInput(inputId = "fatt_compl_risp",label = "",value = "")),
                                       column(8,
                                              plotOutput('fatt_compl_figura_risp')),
                                       column(8,
                                              h3("Parametri regressione"),
                                              h4("Stima puntuale"),
                                              verbatimTextOutput('fatt_compl_coeff'),
                                              uiOutput('fatt_compl_stimint_txt'),
                                              verbatimTextOutput('fatt_compl_stimint')),
                                       column(12,
                                              hr(),
                                              plotOutput('fatt_compl_grcoeff')),
                                       column(12,
                                              plotOutput('fatt_compl_grsigncoeff')),
                                       column(12,
                                              hr(),
                                              h3("Grafico superficie risposta"),
                                              uiOutput('fatt_compl_selvar_spazio')
                                              ),
                                       column(3,
                                              uiOutput('fatt_compl_mod_selvar')),
                                       column(6,
                                              uiOutput("fatt_compl_mod_fixvar")),
                                       column(12),
                                       column(6,
                                              plotOutput('fatt_compl_livellorisp', width = "100%", height = "500px"),
                                              uiOutput("fatt_compl_livellorisp_col")),
                                       column(6,
                                              plotOutput('fatt_compl_suprisp', width = "100%", height = "500px")),
                                       column(6),
                                       column(3,
                                              br(),
                                              div(style='font-size: 80%; width: 90%;',
                                                  uiOutput('fatt_compl_rp_z'))),
                                       column(3,
                                              br(),
                                              div(style='font-size: 80%; width: 90%;',
                                                  uiOutput('fatt_compl_rp_x'))),
                                       column(12,hr()),
                                       column(5,
                                              textInput(inputId = "fatt_compl_prev",label = "Punto previsione (coord.separate da spazio)",value = ""),
                                              verbatimTextOutput('fatt_compl_prev_df'),
                                              verbatimTextOutput('fatt_compl_intprev')),
                                       column(2),
                                       column(3,
                                              textInput(inputId = "fatt_compl_misind",label = "Misure indipendenti",value = ""),
                                              verbatimTextOutput('fatt_compl_misind_media'),
                                              verbatimTextOutput('fatt_compl_misind_sd'),
                                              verbatimTextOutput('fatt_compl_misind_gdl')))))),

    tabItem(tabName = "frazion",
        fluidPage(titlePanel(uiOutput("frazion_titolo")),
                  tabsetPanel(type = "tabs",
                              tabPanel("Disegno",
                                       column(12,
                                              br(),
                                              imageOutput("logo"),
                                              br()),
                                       column(4,
                                              numericInput("frazion_k",label="n° fattori",width = "25%",value = 3,min = 3),
                                              numericInput("frazion_p",label="n° generatori",width = "25%",value = 1)),
                                       
                                       column(6,
                                              hr(),hr(),
                                              h5('Generatori'),
                                              verbatimTextOutput("frazion_generat")),
                                       column(12),
                                       column(4,
                                              h4('Disegno'),
                                              tableOutput("frazion_dis"),
                                              downloadButton("frazion_download")),
                                       column(12),
                                       column(4,
                                              hr(),
                                              h4('Modello'),
                                              textOutput("frazion_modello")),
                                       column(8,
                                              h5("Confusioni"),
                                              verbatimTextOutput("frazion_confusioni")),
                                       column(12,
                                              hr(),
                                              h4('Matrice di dispersione'),
                                              div(style = 'overflow-x: scroll',tableOutput("frazion_matrdisp"))),
                                       column(12,br(),
                                              h3('Grafico Leverage')),
                                       column(3,
                                              uiOutput('frazion_selvar')),
                                       column(6,
                                              uiOutput('frazion_fixvar')),
                                       column(12),
                                       column(6,
                                              plotOutput('frazion_livellolev', width = "100%", height = "500px")),
                                       column(6,
                                              plotOutput('frazion_suplev', width = "100%", height = "500px")),
                                       column(6),
                                       column(3,
                                              br(),
                                              div(style='font-size: 80%; width: 90%;',
                                                  uiOutput('frazion_lv_z'))),
                                       column(3,
                                              br(),
                                              div(style='font-size: 80%; width: 90%;',
                                                  uiOutput('frazion_lv_x')))),
                              
                              tabPanel("Modello",
                                       column(4,
                                              br(),
                                              uiOutput('frazion_risptext'),
                                              textInput(inputId = "frazion_risp",label = "",value = "")),
                                       column(8,
                                              plotOutput('frazion_figura_risp')),
                                       column(8,
                                              h3("Parametri regressione"),
                                              h4("Stima puntuale"),
                                              verbatimTextOutput('frazion_coeff'),
                                              uiOutput('frazion_stimint_txt'),
                                              verbatimTextOutput('frazion_stimint')),
                                       column(12,
                                              hr(),
                                              plotOutput('frazion_grcoeff')),
                                       column(12,
                                              plotOutput('frazion_grsigncoeff')),
                                       column(12,
                                              hr(),
                                              h3("Grafico superficie risposta"),
                                              uiOutput('frazion_selvar_spazio')),
                                       column(3,
                                              uiOutput('frazion_mod_selvar')),
                                       column(6,
                                              uiOutput('frazion_mod_fixvar')),
                                       column(12),
                                       column(6,
                                              plotOutput('frazion_livellorisp', width = "100%", height = "500px"),
                                              uiOutput("frazion_livellorisp_col")),
                                       column(6,
                                              plotOutput('frazion_suprisp', width = "100%", height = "500px")),
                                       column(6),
                                       column(3,
                                              br(),
                                              div(style='font-size: 80%; width: 90%;',
                                                  uiOutput('frazion_rp_z'))),
                                       column(3,
                                              br(),
                                              div(style='font-size: 80%; width: 90%;',
                                                  uiOutput('frazion_rp_x'))),
                                       column(12,hr()),
                                       column(5,
                                              textInput(inputId = "frazion_prev",label = "Punto previsione (coord.separate da spazio)",value = ""),
                                              verbatimTextOutput('frazion_prev_df'),
                                              verbatimTextOutput('frazion_intprev')),
                                       column(2),
                                       column(3,
                                              textInput(inputId = "frazion_misind",label = "Misure indipendenti",value = ""),
                                              verbatimTextOutput('frazion_misind_media'),
                                              verbatimTextOutput('frazion_misind_sd'),
                                              verbatimTextOutput('frazion_misind_gdl')))))),

    tabItem(tabName = "pb",
            fluidPage(titlePanel(uiOutput("pb_titolo")),
                      tabsetPanel(type = "tabs",
                                  tabPanel("Disegno",
                                           column(12,
                                                  br(),
                                                  br()),
                                           column(4,
                                                  numericInput("pb_k",label="n° fattori",width = "25%",value = 5,min = 5),
                                                  uiOutput("pb_n")),
                                           column(8,
                                                  uiOutput("dis16"),
                                                  span(uiOutput("pb_suggerimento"), style="color:red")),
                                           column(12),
                                           column(4,
                                                  h4('Disegno'),
                                                  tableOutput("pb_dis"),
                                                  downloadButton("pb_download")),
                                           column(12),
                                           column(4,
                                                  hr(),
                                                  h4('Modello'),
                                                  textOutput("pb_modello")),
                                           column(8,
                                                  h5("Confusioni"),
                                                  verbatimTextOutput("pb_confusioni")),
                                           column(12,
                                                  hr(),
                                                  h4('Matrice di dispersione'),
                                                  div(style = 'overflow-x: scroll',tableOutput("pb_matrdisp"))
                                                  )),
                                  
                                  tabPanel("Modello",
                                           column(4,
                                                  br(),
                                                  uiOutput('pb_risptext'),
                                                  textInput(inputId = "pb_risp",label = "",value = "")),
                                           column(8,
                                                  plotOutput('pb_figura_risp')),
                                           column(8,
                                                  h3("Parametri regressione"),
                                                  h4("Stima puntuale"),
                                                  verbatimTextOutput('pb_coeff'),
                                                  uiOutput('pb_stimint_txt'),
                                                  verbatimTextOutput('pb_stimint')),
                                           column(12,
                                                  hr(),
                                                  plotOutput('pb_grcoeff')),
                                           column(12,
                                                  plotOutput('pb_grsigncoeff')),
                                           column(12,
                                                  hr(),hr(),h3("Plot alias"),hr(),
                                                  plotOutput("pb_graf_alias")))))),

    tabItem(tabName = "ccd",
            fluidPage(titlePanel(uiOutput("ccd_titolo")),
                      tabsetPanel(type = "tabs",
                                  tabPanel("Disegno",
                                           column(12,
                                                  br()),
                                           column(4,
                                                  numericInput("ccd_k",label="n° fattori",width = "25%",value = 2,min = 2),
                                                  numericInput("ccd_n",label="n° punti al centro",width = "25%",value = 1),
                                                  selectInput("ccd_alfa", label = "tipo:", 
                                                              choices = list("ruotabile" = 1, "sferico" = 2, "facce centrate" = 3, "ortogonale" = 4), 
                                                              selected = 1,width="130px"),
                                                 # hr(),
                                                  h4('Disegno'),
                                                  tableOutput("ccd_dis"),
                                                  downloadButton("ccd_download")),
                                           column(8,
                                                  plotOutput('ccd_figura_dis')),
                                           column(12,
                                                  hr(),
                                                  h4('Modello'),
                                                  textOutput("ccd_modello")),
                                           column(12,
                                                  hr(),
                                                  h4('Matrice di dispersione'),
                                                  div(style = 'overflow-x: scroll',tableOutput("ccd_matrdisp"))),
                                           column(12,br(),
                                                  h3('Grafico Leverage')),
                                           column(3,
                                                  uiOutput('ccd_selvar')),
                                           column(6,
                                                  uiOutput('ccd_fixvar')),
                                           column(12),
                                           column(6,
                                                  plotOutput('ccd_livellolev', width = "100%", height = "500px")),
                                           column(6,
                                                  plotOutput('ccd_suplev', width = "100%", height = "500px")),
                                           column(6),
                                           column(3,
                                                  br(),
                                                  div(style='font-size: 80%; width: 90%;',
                                                      uiOutput('ccd_lv_z'))),
                                           column(3,
                                                  br(),
                                                  div(style='font-size: 80%; width: 90%;',
                                                      uiOutput('ccd_lv_x')))),
                                  
                                  tabPanel("Modello",
                                           column(4,
                                                  br(),
                                                  uiOutput('ccd_risptext'),
                                                  textInput(inputId = "ccd_risp",label = "",value = "")),
                                           column(8,
                                                  plotOutput('ccd_figura_risp')),
                                           column(8,
                                                  h3("Parametri regressione"),
                                                  h4("Stima puntuale"),
                                                  verbatimTextOutput('ccd_coeff'),
                                                  uiOutput('ccd_stimint_txt'),
                                                  verbatimTextOutput('ccd_stimint')),
                                           column(12,
                                                  hr(),
                                                  plotOutput('ccd_grcoeff')),
                                           column(12,
                                                  hr(),
                                                  h3("Grafico superficie risposta"),
                                                  uiOutput('ccd_selvar_spazio')),
                                           column(3,
                                                  uiOutput('ccd_mod_selvar')),
                                           column(6,
                                                  uiOutput("ccd_mod_fixvar")),
                                           column(12),
                                           column(6,
                                                  plotOutput('ccd_livellorisp', width = "100%", height = "500px"),
                                                  uiOutput("ccd_livellorisp_col")),
                                           column(6,
                                                  plotOutput('ccd_suprisp', width = "100%", height = "500px")),
                                           column(6),
                                           column(3,
                                                  br(),
                                                  div(style='font-size: 80%; width: 90%;',
                                                      uiOutput('ccd_rp_z'))),
                                           column(3,
                                                  br(),
                                                  div(style='font-size: 80%; width: 90%;',
                                                      uiOutput('ccd_rp_x'))),
                                           column(12,hr()),
                                           column(5,
                                                  textInput(inputId = "ccd_prev",label = "Punto previsione (coord.separate da spazio)",value = ""),
                                                  verbatimTextOutput('ccd_prev_df'),
                                                  verbatimTextOutput('ccd_intprev')),
                                           column(2),
                                           column(3,
                                                  textInput(inputId = "ccd_misind",label = "Misure indipendenti",value = ""),
                                                  verbatimTextOutput('ccd_misind_media'),
                                                  verbatimTextOutput('ccd_misind_sd'),
                                                  verbatimTextOutput('ccd_misind_gdl')))))),

    tabItem(tabName = "d_opt",
            fluidPage(titlePanel(uiOutput("d_opt_titolo")),
                      tags$head(
                        tags$style(HTML(".shiny-output-error-validation {color: red;font-size: 130%; "))
                      ),
                      tabsetPanel(type = "tabs",
                                  tabPanel("Matrice punti candidati",
                                           column(12,
                                                  br()),
                                           column(4,
                                                  radioButtons("d_opt_pti_cand", label = "Matrice punti candidati:",
                                                               choices = list("Costruisci" = 1, "Importa" = 2), 
                                                               selected = 1,inline = TRUE),
                                                  br(),
                                                  uiOutput('d_opt_costruisci')),
                                           column(4,
                                                  uiOutput('d_opt_importa')),
                                           column(4,
                                                  uiOutput('d_opt_importa_incolla_spazio'),
                                                  uiOutput('d_opt_importa_incolla'),
                                                  uiOutput('d_opt_importa_incolla_spazio1'),
                                                  uiOutput('d_opt_importa_excel_brws')),
                                           column(12),
                                           column(4,
                                                  uiOutput('d_opt_nvar')),
                                          column(8,
                                                 htmlOutput("d_opt_lev_var1"),
                                                 htmlOutput("d_opt_lev_var2"),
                                                 htmlOutput("d_opt_lev_var3"),
                                                 htmlOutput("d_opt_lev_var4"),
                                                 htmlOutput("d_opt_lev_var5"),
                                                 htmlOutput("d_opt_lev_var6"),
                                                 htmlOutput("d_opt_lev_var7"),
                                                 htmlOutput("d_opt_lev_var8"),
                                                 htmlOutput("d_opt_lev_var9"),
                                                 htmlOutput("d_opt_lev_var10"),
                                                 htmlOutput("d_opt_lev_var11"),
                                                 htmlOutput("d_opt_lev_var12"),
                                                 htmlOutput("d_opt_lev_var13"),
                                                 htmlOutput("d_opt_lev_var14"),
                                                 htmlOutput("d_opt_lev_var15"),
                                                 htmlOutput("d_opt_lev_var16"),
                                                 htmlOutput("d_opt_lev_var17"),
                                                 htmlOutput("d_opt_lev_var18"),
                                                 htmlOutput("d_opt_lev_var19"),
                                                 htmlOutput("d_opt_lev_var20"),
                                                 htmlOutput("d_opt_lev_var21"),
                                                 htmlOutput("d_opt_lev_var22"),
                                                 htmlOutput("d_opt_lev_var23"),
                                                 htmlOutput("d_opt_lev_var24"),
                                                 htmlOutput("d_opt_lev_var25"),
                                                 htmlOutput("d_opt_lev_var26"),
                                                 htmlOutput("d_opt_lev_var27"),
                                                 htmlOutput("d_opt_lev_var28"),
                                                 htmlOutput("d_opt_lev_var29"),
                                                 htmlOutput("d_opt_lev_var30"),
                                                 htmlOutput("d_opt_lev_var31"),
                                                 htmlOutput("d_opt_lev_var32"),
                                                 htmlOutput("d_opt_lev_var33"),
                                                 htmlOutput("d_opt_lev_var34"),
                                                 htmlOutput("d_opt_lev_var35"),
                                                 htmlOutput("d_opt_lev_var36"),
                                                 htmlOutput("d_opt_lev_var37"),
                                                 htmlOutput("d_opt_lev_var38"),
                                                 htmlOutput("d_opt_lev_var39"),
                                                 htmlOutput("d_opt_lev_var40"),
                                                 htmlOutput("d_opt_lev_var41"),
                                                 htmlOutput("d_opt_lev_var42"),
                                                 htmlOutput("d_opt_lev_var43"),
                                                 htmlOutput("d_opt_lev_var44"),
                                                 htmlOutput("d_opt_lev_var45"),
                                                 htmlOutput("d_opt_lev_var46"),
                                                 htmlOutput("d_opt_lev_var47"),
                                                 htmlOutput("d_opt_lev_var48"),
                                                 htmlOutput("d_opt_lev_var49"),
                                                 htmlOutput("d_opt_lev_var50")),
                                          column(12),
                                          column(4,
                                                uiOutput('d_opt_passo')),
                                          column(12,
                                                 h4('Matrice punti candidati'),
                                                 radioButtons("d_opt_cp_ha", "Display",choices = c('Head' = 1,"All" =2),selected = 1,inline=TRUE),
                                                 div(style = 'overflow-x: scroll',tableOutput("d_opt_cp")),
                                                 downloadButton("d_opt_download"))
                                           ),
                                  tabPanel('D-ottimale',
                                           column(12,
                                                  br()),
                                           column(6,
                                                  checkboxGroupInput("d_opt_mod_tipo", label = 'Modello con:',inline = TRUE,
                                                                     choices = list("Intercetta" = 1,'Termini di ordine superiore'=2),selected = c(1,2))),
                                           column(6,
                                                  uiOutput("d_opt_mod_variabx")),
                                           column(12,
                                                  hr(),
                                                  h4('Modello'),
                                                  textOutput("d_opt_modello")),
                                           column(12,
                                                  br()),
                                           column(6,
                                                  htmlOutput('d_opt_Lnumexp'),
                                                  actionButton('d_opt_calc','Calcola'),
                                                  hr()),
                                           column(6,
                                                  htmlOutput('d_opt_Unumexp')),
                                           column(12,
                                                  tableOutput('d_opt_table'),
                                                  tableOutput('d_opt_msg1'),
                                                  br()),
                                           column(6,
                                                  plotOutput('d_opt_graf_D')),
                                           column(6,
                                                  plotOutput('d_opt_graf_Vif')),
                                           column(12,
                                                  br()),
                                           column(8,
                                                  uiOutput('d_opt_numexp')),
                                           column(12,
                                                  #uiOutput('d_opt_numexp'),
                                                  h4('Disegno D-ottimale'),
                                                  div(style = 'overflow-x: scroll',tableOutput("d_opt_dis_opt")),
                                                  downloadButton("d_opt_dis_download"),
                                                  hr(),
                                                  h5('VIF'),
                                                  div(style = 'overflow-x: scroll',tableOutput("d_opt_vf")))
                                           ),
                                  tabPanel('D-ottimale per aggiunta',
                                           column(12,
                                                  br()),
                                           column(4,
                                                  radioButtons("d_opt_ag_importa", label = "Importa disegno:",
                                                               choices = list("Incolla" = 1, "Excel" = 2), 
                                                               selected = 1,inline = TRUE)),
                                           column(4,
                                                  uiOutput('d_opt_ag_importa_incolla_spazio'),
                                                  uiOutput('d_opt_ag_importa_incolla'),
                                                  uiOutput('d_opt_ag_importa_incolla_spazio1'),
                                                  uiOutput('d_opt_ag_importa_excel_brws')),
                                           column(12,
                                                  h4('Disegno exp. già eseguiti'),
                                                  tableOutput("d_opt_dis_tbl")),
                                           column(12,
                                                  br()),
                                           column(6,
                                                  checkboxGroupInput("d_opt_ag_mod_tipo", label = 'Modello con:',inline = TRUE,
                                                                     choices = list("Intercetta" = 1,'Termini di ordine superiore'=2),selected = c(1,2))),
                                           column(6,
                                                  uiOutput("d_opt_ag_mod_variabx")),
                                           column(12,
                                                  hr(),
                                                  h4('Modello'),
                                                  textOutput("d_opt_ag_modello")),
                                           column(12,
                                                  br()),
                                           column(6,
                                                  htmlOutput('d_opt_ag_Lnumexp'),
                                                  actionButton('d_opt_ag_calc','Calcola'),
                                                  hr()),
                                           column(6,
                                                  htmlOutput('d_opt_ag_Unumexp')),
                                           column(12,
                                                  tableOutput('d_opt_ag_table'),
                                                  tableOutput('d_opt_ag_msg1_tb'),
                                                  tableOutput('d_opt_ag_msg2_tb'),
                                                  tableOutput('d_opt_ag_msg3_tb'),
                                                  br()),
                                           column(6,
                                                  plotOutput('d_opt_ag_graf_D')),
                                           column(6,
                                                  plotOutput('d_opt_ag_graf_Vif')),
                                           column(12,
                                                  br()),
                                           column(8,
                                                  uiOutput('d_opt_ag_numexp')),
                                           column(12,
                                                 # uiOutput('d_opt_ag_numexp'),
                                                  h4('Disegno D-ottimale'),
                                                  h6(uiOutput('d_opt_ag_expes')),
                                                  div(style = 'overflow-x: scroll',tableOutput("d_opt_ag_dis_opt")),
                                                  downloadButton("d_opt_ag_dis_download"),
                                                  hr(),
                                                  h5('VIF'),
                                                  div(style = 'overflow-x: scroll',tableOutput("d_opt_ag_vf")))
                                  )
                                  ))),
    tabItem(tabName = "pp",
            fluidPage(titlePanel(uiOutput("pp_titolo")),
                      tags$head(
                        tags$style(HTML(".shiny-output-error-validation {color: red;font-size: 130%; "))
                      ),
                      tabsetPanel(type = "tabs",
                                  tabPanel("Disegno",
                                           column(12,
                                                  br()),
                                           column(4,
                                                  radioButtons("pp_importa", label = "Importa disegno:",
                                                               choices = list("Incolla" = 1, "Excel" = 2), 
                                                               selected = 1,inline = TRUE)),
                                           column(4,
                                                  uiOutput('pp_importa_incolla_spazio'),
                                                  uiOutput('pp_importa_incolla'),
                                                  uiOutput('pp_importa_incolla_spazio1'),
                                                  uiOutput('pp_importa_excel_brws')),
                                           column(12,
                                                  h4('Disegno'),
                                                  tableOutput("pp_dis")),
                                           column(6,
                                                  checkboxGroupInput("pp_mod_tipo", label = 'Modello con:',inline = TRUE,
                                                                     choices = list("Intercetta" = 1,'Termini di ordine superiore'=2),selected = c(1,2))),
                                           column(6,
                                                  uiOutput("pp_mod_variabx")),
                                           column(12,
                                                  hr(),
                                                  h4('Modello'),
                                                  textOutput("pp_modello")),
                                           column(12,
                                                  hr(),
                                                  h4('Matrice di dispersione'),
                                                  div(style = 'overflow-x: scroll',tableOutput("pp_matrdisp"))),
                                           column(12,br(),
                                                  h3('Grafico Leverage')),
                                         #  column(5,
                                         #         uiOutput('pp_selinteraz')),
                                           column(3,
                                                  uiOutput('pp_selvar')),
                                           column(6,
                                                  uiOutput('pp_fixvar')),
                                           column(12),
                                           column(6,
                                                  plotOutput('pp_livellolev', width = "100%", height = "500px")),
                                           column(6,
                                                  plotOutput('pp_suplev', width = "100%", height = "500px")),
                                         column(6),
                                         column(3,
                                                br(),
                                                div(style='font-size: 80%; width: 90%;',
                                                    uiOutput('pp_lv_z'))),
                                         column(3,
                                                br(),
                                                div(style='font-size: 80%; width: 90%;',
                                                    uiOutput('pp_lv_x')))),
                                  tabPanel("Modello",
                                           column(4,
                                                  br(),
                                                  uiOutput('pp_risptext'),
                                                  textInput(inputId = "pp_risp",label = "",value = "")),
                                           column(8,
                                                  plotOutput('pp_figura_risp')),
                                           column(8,
                                                  h3("Parametri regressione"),
                                                  h4("Stima puntuale"),
                                                  verbatimTextOutput('pp_coeff'),
                                                  uiOutput('pp_stimint_txt'),
                                                  verbatimTextOutput('pp_stimint')),
                                           column(2),
                                           column(2,
                                                  radioButtons("pp_resind", label = h3("Stima della varianza da:"),
                                                               choices = list("Residui" = 1, "Misure indipendenti" = 2), 
                                                              selected = 1)),
                                           column(12,
                                                  hr(),
                                                  plotOutput('pp_grcoeff')),
                                           column(12,
                                                  plotOutput('pp_grsigncoeff')),
                                           column(12,
                                                  hr(),
                                                  h3("Grafico superficie risposta"),
                                                  uiOutput('pp_selvar_spazio')),
                                          # column(5,
                                          #        uiOutput('pp_mod_selinteraz')),
                                           column(3,
                                                  uiOutput('pp_mod_selvar')),
                                           column(6,
                                                  uiOutput("pp_mod_fixvar")),
                                           column(12),
                                           column(6,
                                                  plotOutput('pp_livellorisp', width = "100%", height = "500px"),
                                                  uiOutput("pp_livellorisp_col")),
                                           column(6,
                                                  plotOutput('pp_suprisp', width = "100%", height = "500px")),
                                           column(6),
                                           column(3,
                                                 br(),
                                                 div(style='font-size: 80%; width: 90%;',
                                                     uiOutput('pp_rp_z'))),
                                           column(3,
                                                 br(),
                                                 div(style='font-size: 80%; width: 90%;',
                                                     uiOutput('pp_rp_x'))),
                                           column(12,hr()),
                                           column(5,
                                                  textInput(inputId = "pp_prev",label = "Punto previsione (coord.separate da spazio)",value = ""),
                                                  verbatimTextOutput('pp_prev_df'),
                                                  verbatimTextOutput('pp_intprev')),
                                           column(2),
                                           column(3,
                                                  textInput(inputId = "pp_misind",label = "Misure indipendenti",value = ""),
                                                  verbatimTextOutput('pp_misind_media'),
                                                  verbatimTextOutput('pp_misind_sd'),
                                                  verbatimTextOutput('pp_misind_gdl')))))),
    
    
    
    
    
    
    
    
    
    
    
    tabItem(tabName = "m_simplex",
            fluidPage(titlePanel(uiOutput("m_simplex_titolo")),
                      tabsetPanel(type = "tabs",
                                  tabPanel("Disegno",
                                           column(12,
                                                  br()),
                                           column(4,
                                                  selectInput("m_simplex_mod",label="modello",width = "45%",
                                                              choices = list('lineare'=1,'quadratico'=2,'cubico'=3)),
                                                  h4('Disegno'),
                                                  tableOutput("m_simplex_dis"),
                                                  checkboxInput("m_simplex_axial", label = "punti assiali", value = FALSE),
                                                  downloadButton("m_simplex_download")),
                                           column(8,
                                                  plotOutput('m_simplex_figura_dis')),
                                           column(12,
                                                  hr(),
                                                  hr(),
                                                  hr(),
                                                  hr(),
                                                  hr(),
                                                  h4('Modello'),
                                                  textOutput("m_simplex_modello")),
                                           column(3,
                                                  hr(),
                                                  h4('Matrice di dispersione'),
                                                  div(style = 'overflow-x: scroll;',tableOutput("m_simplex_matrdisp"))
                                           ),
                                           column(1),
                                          #◘ column(4,
                                           #       hr()),
                                           column(8,br(),
                                                  h3('Grafico Leverage'),
                                                  plotOutput('m_simplex_livellolev', width = "100%", height = "500px"))),
                                  
                                  tabPanel("Modello",
                                           column(4,
                                                  br(),
                                                  uiOutput('m_simplex_risptext'),
                                                  textInput(inputId = "m_simplex_risp",label = "",value = "")),
                                           column(8,
                                                  plotOutput('m_simplex_figura_risp')),
                                           column(8,
                                                  h3("Parametri regressione"),
                                                  h4("Stima puntuale"),
                                                  verbatimTextOutput('m_simplex_coeff'),
                                                  uiOutput('m_simplex_stimint_txt'),
                                                  verbatimTextOutput('m_simplex_stimint')),
                                           column(12,
                                                  hr(),
                                                  plotOutput('m_simplex_grcoeff')),
                                           column(12,
                                                  plotOutput('m_simplex_grsigncoeff')),
                                           column(12,
                                                  hr(),
                                                  h3("Grafico superficie risposta"),
                                                  uiOutput('m_simplex_selvar_spazio')
                                           ),
                                           column(3,
                                                  uiOutput('m_simplex_mod_selvar')),
                                           column(6,
                                                  uiOutput("m_simplex_mod_fixvar")),
                                           column(12),
                                           column(6,
                                                  plotOutput('m_simplex_livellorisp', width = "100%", height = "500px"),
                                                  uiOutput("m_simplex_livellorisp_col")),
                                           column(6,
                                                  plotOutput('m_simplex_suprisp', width = "100%", height = "500px")),
                                           column(6),
                                           column(3,
                                                  br(),
                                                  div(style='font-size: 80%; width: 90%;',
                                                      uiOutput('m_simplex_rp_z'))),
                                           column(3,
                                                  br(),
                                                  div(style='font-size: 80%; width: 90%;',
                                                      uiOutput('m_simplex_rp_x'))),
                                           column(12,hr()),
                                           column(5,
                                                  textInput(inputId = "m_simplex_prev",label = "Punto previsione (coord.separate da spazio)",value = ""),
                                                  verbatimTextOutput('m_simplex_prev_df'),
                                                  verbatimTextOutput('m_simplex_intprev')),
                                           column(2),
                                           column(3,
                                                  textInput(inputId = "m_simplex_misind",label = "Misure indipendenti",value = ""),
                                                  verbatimTextOutput('m_simplex_misind_media'),
                                                  verbatimTextOutput('m_simplex_misind_sd'),
                                                  verbatimTextOutput('m_simplex_misind_gdl'))))))
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    

    
    
    
    
    
    
    
    
    
    
    
    
    

 
    
    
    
    ))


































ui <- dashboardPage(skin="purple",header, sidebar, body)


